---
kind: pipeline
name: tests

steps:
- name: go tests
  image: golang:alpine
  commands:
  - apk --no-cache add gcc git musl-dev
  - go install github.com/frebib/enumerx@latest

  - go generate
  - go build -o nzbget_exporter

  - go install golang.org/x/tools/cmd/goimports@latest
  - go install golang.org/x/lint/golint@latest
  - test -z "$(gofmt -l . | tee /dev/stderr)"
  - test -z "$(goimports -local -e -d . | tee /dev/stderr)"
  - golint ./...
  - go test -covermode atomic ./...

---
kind: pipeline
name: docker

depends_on:
- tests

steps:
- name: docker build
  image: registry.spritsail.io/spritsail/docker-build
  pull: always

- name: docker publish spritsail
  image: registry.spritsail.io/spritsail/docker-publish
  pull: always
  settings:
    registry: registry.spritsail.io
    login: {from_secret: spritsail_login}
    repo: frebib/nzbget-exporter
    tags: &tags
    - latest
    - '%label org.label-schema.version'
    delete: no
  depends_on:
    - docker build
  when:
    branch:
    - master
    event:
    - push

- name: docker publish ghcr
  image: registry.spritsail.io/spritsail/docker-publish
  pull: never
  settings:
    registry: ghcr.io
    login: {from_secret: ghcr_login}
    repo: frebib/nzbget-exporter
    tags: *tags
    delete: no
  depends_on:
    - docker build
  when:
    branch:
    - master
    event:
    - push

- name: docker publish docker hub
  image: registry.spritsail.io/spritsail/docker-publish
  pull: never
  settings:
    login: {from_secret: docker_login}
    repo: frebib/nzbget-exporter
    tags: *tags
  depends_on:
    - docker publish spritsail
    - docker publish ghcr
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: update-readme

depends_on:
- docker

steps:
- name: dockerhub-readme
  pull: always
  image: jlesage/drone-push-readme
  settings:
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
    repo: frebib/nzbget-exporter
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 1b70cfb8a9cdff6450ac0985f33e215b36694bb896c42b8edca5fe15ff7c28ef

...
